version: '3'

services:
  backend:
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    container_name: backend
    tty: true
    restart: always
    env_file:
      - ./.env
    volumes:
      - type: bind
        source: ./srcs/backend
        target: /app
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
    container_name: frontend
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./srcs/frontend
        target: /app
    ports:
      - 5173:5173
